require: rubocop-rails

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 350

Metrics/CyclomaticComplexity:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 13
